export const HOME = "/"
export const LOGIN = "/login"
export const REGISTER = "/register"
export const FORGOTPASSWORD = "/forgot"
export const DASHBOARD = "/dashboard"
export const BLOGS = "/blogs"
export const NEW_BLOG = "/blog/new"