export const API_baseURL = "http://localhost:3000/api"
export const API_ROUTE_LOGIN = "/auth/login"
export const API_ROUTE_REGISTER = "/auth/register"
export const API_ROUTE_FORGOT_PASSWORD = "/auth/send-password-reset"
export const API_ROUTE_NEW_BLOG = "/user/blog"